import "@/styles/globals.css";

import { Inter } from "next/font/google";
import Provider from "./_components/provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`min-h-screen font-sans ${inter.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
